---
- hosts: all
  become: true
  pre_tasks:

  - name: Update Respository Index (CentOS)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: Install Epel-release (Centos)
    tags: always
    dnf:
      name: epel-release
    when: ansible_distribution == "CentOS"

  - name: Install Updates (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"


- hosts: ubuntu
  become: true
  roles:
    - nagios

- hosts: centos
  become: true
  roles:
    - prometheus
